### ISSUE TITLE
rename OneSignal.define as Onesignal.configure

### ISSUE THREAD

**Issue by spaghetticode** [mikamai/onesignal-ruby#1]
While there is nothing inherently wrong with using `OneSignal.define` I think that `Onesignal.configure` would be a slightly better choice. 

According to the principle of least surprise many developers may be already accustomed to `configure` as many other Ruby libraries use the same method name for that configuration pattern (Rails, Rspec, Capybara, Rollbar, Solidus just to name a few I can recall). 

Of course in order to make things easier and avoid breaking any existing code the `define` method could be simply aliased to `configure`.

**Comment by MatteoJoliveau** [comment]
That's a valid point. I'll refactor it right away

**Comment by MatteoJoliveau** [comment]
Closed by [95f07f3](https://github.com/mikamai/onesignal-ruby/commit/95f07f3340368ffa38e08751015889fee8cdbba3)
