### ISSUE TITLE
This is not a real issue It's a question

### ISSUE THREAD

**Issue by certilremy** [mikamai/onesignal-ruby#18]
Hi, Thank you all for this amazing Gem. Actually this is not an issue. Is there any example or possible way of how to send a push notification to a single user using this gem?

**Comment by MatteoJoliveau** [comment]
Hi! This library is only a thin wrapper around OneSignal REST API, so if it's implemented it works the same way as the HTTP API.

In your particular case, you can use one of the strategy shown [here](https://documentation.onesignal.com/docs/transactional-messages) as we support both `include_player_ids` and `include_external_user_ids` parameters.

For example, assuming you have a user with a registered External User ID of `user-1`, you can send them a notification by creating one like such:

```ruby

included_targets = OneSignal::IncludedTargets.new(include_external_user_ids: ['user-1'])

notification = OneSignal::Notification.new(headings: my_headings, contents: my_contents, included_targets: included_targets)
```

You can fine other examples [in the README](https://github.com/mikamai/onesignal-ruby#specific-targets)

**Comment by certilremy** [comment]
Thank you, I understand it now

**Comment by MatteoJoliveau** [comment]
My pleasure!
Feel free to open a new issue if you encounter any problem.
