### ISSUE TITLE
ERROR:  Could not find a valid gem 'onesignal-ruby

### ISSUE THREAD

**Issue by certilremy** [mikamai/onesignal-ruby#19]
``gem install onesignal-ruby, '~> 0.4' ``
ERROR:  Could not find a valid gem 'onesignal-ruby,' (>= 0) in any repository
ERROR:  Possible alternatives: onesignal-ruby, one_signal, onesignal, EsignRuby, functional-ruby
ERROR:  Could not find a valid gem '~> 0.4' (>= 0) in any repository

Rails 6.0.2

**Comment by MatteoJoliveau** [comment]
Hi, version 0.4 is not yet available on RubyGems. We'll see what we can do to release it

**Comment by certilremy** [comment]
I can't install the version 3 on rails 6. I downgrade the app to version 5.2.3, it seems like the gem is looking for a service worker file. I saw this in the console

```  
Started GET "/serviceworker.js" for ::1 at 2020-07-01 10:54:37 -0400
  
ActionController::RoutingError (No route matches [GET] "/serviceworker.js"):

**Comment by MatteoJoliveau** [comment]
This error it totally unrelated with the gem. We do not have any browser-related asset nor we handle any HTTP route. It's just an HTTP client.

**Comment by jamesdixon** [comment]
Hi, any update on releasing this? Can't currently install as I'm on Rails 6

**Comment by certilremy** [comment]
> Hi, any update on releasing this? Can't currently install as I'm on Rails 6

You can get it from the dev branch.
`gem 'onesignal-ruby', github: 'mikamai/onesignal-ruby', branch: 'develop'`

**Comment by kevTheDev** [comment]
Hi,

Any plans to release the official 0.4.0 soon? Or anything I can do to help?

**Comment by bernardini687** [comment]
hi, 0.4.0 will hopefully be released by the end of next week!

**Comment by bernardini687** [comment]
hello again, 0.4.0 is finally released: https://rubygems.org/gems/onesignal-ruby/versions/0.4.0
