### ISSUE TITLE
ETA for push on rubygems

### ISSUE THREAD

**Issue by gabriel-dehan** [mikamai/onesignal-ruby#2]
Hello! 

Great work and great gem, was wondering if you could deploy it on rubygems? It'd be nice to have a master branch too :P 
Also, in the readme, it'd be rather helpful to add that you need to `require 'onesignal'` in your initializer :) 

Cheers

**Comment by gabriel-dehan** [comment]
This is like the only up-to-date and decent library for OneSignal ruby and it is already complete enough  to be used in a production app, in my opinion it could be released as it is nothing prevents you from iterating and I guess most future changes won't break the API :) 

It is also a bit ugly to have to install it from github#develop in the gemfile :p

**Comment by mikefogg** [comment]
Would love to see this on rubygems :) Great work!

**Comment by MatteoJoliveau** [comment]
Hi!
Publishing to rubygems is incoming, I just want to clean up the internals and improve the test coverage.
@gabriel-dehan if you are able to add some tests to your PR, I would be more than happy to merge it!

**Comment by MatteoJoliveau** [comment]
Gem available at https://rubygems.org/gems/onesignal-ruby
