### ISSUE TITLE
Support for rails 7

### ISSUE THREAD

**Issue by tzar** [mikamai/onesignal-ruby#39]
`onesignal-ruby` currently pins rails between 5-6, but 7.0.1 is out:

```
    onesignal-ruby was resolved to 0.6.0, which depends on
      activesupport (>= 5.0.0, < 7)
```

**Comment by delongtj** [comment]
@bernardini687 are there any plans to publish a version with Rails 7 support? We'd like to avoid forking if possible.

**Comment by bernardini687** [comment]
hello @delongtj 
sorry, there are currently no plans for that

**Comment by Zooip** [comment]
You should close this issue, it is solved
