### ISSUE TITLE
Bump version needed

### ISSUE THREAD

**Issue by herohhnparaiso** [mikamai/onesignal-ruby#8]
This is the 0.3.0 onesignal.rb module definition, which is different from the latest in the repo (it's missing the configure method for example).  My guess is that whoever is using this is referencing the repo?

```

require 'onesignal/version'
require 'onesignal/client'
require 'onesignal/request'
require 'onesignal/request_error'
require 'onesignal/app_id_missing_error'
require 'onesignal/models/base_model'
require 'onesignal/models/app'
require 'onesignal/models/player'
require 'onesignal/models/notification'
require 'onesignal/resources/base_resource'
require 'onesignal/resources/app_resource'
require 'onesignal/resources/player_resource'
require 'onesignal/resources/notification_resource'

module OneSignal
  DEVICE_TYPES = %w(
    ios android amazon mpns chrome_app chrome_website wns safari firefox
  ).freeze

  def self.device_type_as_integer(device_type)
    DEVICE_TYPES.index(device_type)
  end
end```

**Comment by MatteoJoliveau** [comment]
Hi @herohhnparaiso, sorry for the long delay, we have resumed maintenance on this repo. We are working on fixing the currently open issues and will release a new version as soon as this is done. :+1:

**Comment by bernardini687** [comment]
0.4.0 is finally released! https://rubygems.org/gems/onesignal-ruby/versions/0.4.0
